import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1200, height: 800 } });
page.on('pageerror', (e) => console.log('[pageerror]', e.message));
page.on('console', (m) => console.log(`[${m.type()}]`, m.text().slice(0, 300)));
await page.addInitScript(() => { try { sessionStorage.setItem('aksoy-pre', '1'); } catch {} });
await page.goto('http://127.0.0.1:4401/?debug', { waitUntil: 'networkidle' });
await page.waitForFunction(() => window.__S, null, { timeout: 90000 });
await page.waitForTimeout(2500);
const info = await page.evaluate(() => {
  const m = window.__mach;
  window.__intro.k = 0;
  const P = m.sP.array, V = m.sV.array;
  const inj = () => { for (let i = 0; i < 20; i++) { m.sAge[i] = 0.1; m.sMax[i] = 1000; P[i*3] = -1 + i*0.1; P[i*3+1] = 0.5; P[i*3+2] = 1; V[i*3] = 0; V[i*3+1] = -8; V[i*3+2] = 0; } requestAnimationFrame(inj); };
  inj();
  const r = window.__renderer;
  return { calls: r.info.render.calls, programs: r.info.programs?.length, sparkVisible: m.fx.children.map(c => c.type + ':' + c.visible) };
});
console.log(JSON.stringify(info));
await page.waitForTimeout(300);
await page.screenshot({ path: 'verify-out/spark3.png' });
await browser.close();
