// English UI strings. Must define every key of the Turkish table (type-checked).
import type { StringKey } from './tr.ts';

export const EN: Record<StringKey, string> = {
  'app.name': 'KANAT',
  'app.tagline': 'Wingsuit flight over the landscapes of Anatolia.',
  'common.ok': 'OK',
  'common.cancel': 'Cancel',
  'common.back': 'Back',
  'common.close': 'Close',
  'common.continue': 'Continue',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.play': 'Fly',
  'common.retry': 'Retry',
  'common.share': 'Share',
  'common.next': 'Next',
  'common.settings': 'Settings',
  'common.locked': 'Locked',
  'common.new': 'New',
  'common.apply': 'Apply',
  'common.copy': 'Copy',
  'common.copied': 'Copied',
  'common.paste': 'Paste',
  'common.stars': '{n, plural, one {# star} other {# stars}}',
  'common.starsOf': '{n}/{total}',
  'common.route': 'Route {n}',
  'common.difficulty': 'Difficulty {n}/9',
  'common.score': 'Score',
  'common.time': 'Time',
  'common.best': 'Best',
  'common.points': '{n, number} pts',
  'common.seconds': '{n, decimal} s',
  'common.metres': '{n} m',
  'common.ai': 'AI',

  'loading.title': 'Loading',
  'loading.preparing': 'Preparing terrain',
  'loading.tip': 'Tip',
  'tip.0': 'Fly close and the score multiplies: under 3 metres is ×5.',
  'tip.1': 'Letting go is always safe; the wings level themselves.',
  'tip.2': 'Thermals refill your energy. Look for the shimmer of heat.',
  'tip.3': 'Thread between two balloons: Balloon Thread +750.',
  'tip.4': 'Open the canopy at 60–90 metres for a Bold Opening bonus.',
  'tip.5': 'Pull down 3 metres above the ground for a soft landing.',
  'tip.6': 'The short line is usually the close line.',
  'tip.7': 'The Daily Route is the same for everyone. Share your card.',
  'tip.8': 'Send a duel code; your flight becomes a ghost on your friend’s screen.',
  'tip.9': 'Nobody gets eaten in SÜRÜ.io: close the ring, win the flock over.',

  'menu.continue': 'Continue',
  'menu.continueSub': '{world}\u00A0· Route\u00A0{n}',
  'menu.firstFlight': 'First flight',
  'menu.firstFlightSub': 'Jump from a balloon basket at Cappadocia dawn',
  'menu.daily': 'Daily Route',
  'menu.dailyBest': 'Best {time, time}',
  'menu.dailyNotYet': 'Not flown today',
  'menu.modes': 'Modes',
  'menu.modesSub': 'Career\u00A0· Duel\u00A0· Free\u00A0Flight',
  'menu.suru': 'SÜRÜ.io',
  'menu.suruSub': '{league} · {lp} LP',
  'menu.collection': 'Collection',
  'menu.collectionSub': '{postcards}/25 postcards\u00A0· {badges}/30\u00A0badges',
  'menu.rank': 'Rank {level}',
  'menu.worlds': 'Worlds',
  'menu.locked': '{cond}',

  'worlds.title': 'Worlds',
  'worlds.stars': '{n}/{total}',
  'worlds.unlockAt': 'Unlocks at {n} stars',
  'worlds.needMore': '{n, plural, one {# more star} other {# more stars}}',
  'worlds.open': 'Routes',
  'worlds.index': 'World {n}',
  'world.kapadokya': 'Cappadocia Dawn',
  'world.likya': 'Lycian Coast',
  'world.karadeniz': 'Black Sea Highlands',
  'world.erciyes': 'Erciyes Snow',
  'world.pamukkale': 'Pamukkale Sunset',
  'worldShort.kapadokya': 'Cappadocia',
  'worldShort.likya': 'Lycia',
  'worldShort.karadeniz': 'Black Sea',
  'worldShort.erciyes': 'Erciyes',
  'worldShort.pamukkale': 'Pamukkale',
  'worldTag.kapadokya': 'Dawn, golden mist and forty balloons',
  'worldTag.likya': 'Turquoise coves in afternoon light',
  'worldTag.karadeniz': 'Highlands beneath a sea of clouds',
  'worldTag.erciyes': 'Blue shadows on a winter afternoon',
  'worldTag.pamukkale': 'Mirror pools at sunset',
  'worldIntro.likya': 'Dive off the cliffs and race your shadow four metres above clear water.',
  'worldIntro.karadeniz': 'Sink into the sea of clouds and burst out past the waterfall.',
  'worldIntro.erciyes': 'Skim the snow ridges and glide beneath the cornices.',
  'worldIntro.pamukkale': 'Fly with your own reflection over pools that hold the sunset.',
  'worldIntro.title': '{world} unlocked',
  'geo.lat': '{v}° N',
  'geo.lon': '{v}° E',

  'routes.title': 'Routes',
  'routes.tasks': 'Master Tasks',
  'routes.bestScore': 'Best score',
  'routes.bestTime': 'Best time',
  'routes.noBest': 'Not flown yet',
  'routes.fly': 'Fly',
  'routes.locked': 'Finish the previous route',
  'routes.jumpFrom': '{type, select, balon {Jump from a balloon basket} ucurum {Jump from the clifftop} other {Jump from the ridge}}',
  'route.w1r1': 'First Jump',
  'route.w1r2': 'Fairy Chimney Slalom',
  'route.w1r3': 'Balloon Road',
  'route.w1r4': 'Pigeon Valley Canyon',
  'route.w2r1': 'Cliffside Glide',
  'route.w2r2': 'Gulet Cove',
  'route.w2r3': 'Rock Arch',
  'route.w2r4': 'Tomb Façade Line',
  'route.w3r1': 'Sea of Clouds',
  'route.w3r2': 'Spruce Corridor',
  'route.w3r3': 'Waterfall Curtain',
  'route.w3r4': 'Highland Low Pass',
  'route.w4r1': 'Snow Ridge',
  'route.w4r2': 'Cornice Edge',
  'route.w4r3': 'Glacier Gully',
  'route.w4r4': 'Summit Descent',
  'route.w5r1': 'Travertine Terraces',
  'route.w5r2': 'Over the Ancient Theatre',
  'route.w5r3': 'Mirror Pools',
  'route.w5r4': 'Sunset Finale',

  'usta.balloonThread': '{count, plural, one {# Balloon Thread} other {# Balloon Threads}}',
  'usta.mult5Hold': '{value} s unbroken at ×5',
  'usta.grazeCount': '{count} skims in one flight',
  'usta.noContact3Stars': '3 stars without a touch',
  'usta.landWithin': 'Land within {value} m of the target',
  'usta.noThermal': 'Finish without a thermal',
  'usta.gateChain': 'Chain {count} gates',
  'usta.allGates': 'Clear every gate',
  'usta.softLanding': 'Make a soft landing',
  'usta.boldOpen': 'Bold Opening (60–90 m)',
  'usta.scoreOver': 'Score over {value, number}',
  'usta.prox3Time': '{value} s total at ×3 or higher',
  'usta.speedOver': 'Top {value} km/h',
  'usta.thermalCount': '{count, plural, one {Ride # thermal} other {Ride # thermals}}',
  'usta.timeUnder': 'Finish under {value} s',
  'usta.waterSkim': '{value} s within 4 m of the water',
  'usta.cloudDive': 'Dive through the sea of clouds',
  'usta.noBounce': 'Finish without a bounce',
  'usta.generic': 'Master Task',

  'rank.0': 'Rookie',
  'rank.1': 'Glider',
  'rank.2': 'Skimmer',
  'rank.3': 'Eagle',
  'rank.4': 'Master',
  'rank.5': 'Legend',
  'rank.level': 'Level {n}',
  'rank.label': 'Pilot Rank',
  'rank.xp': '{xp, number}/{next, number} XP',
  'league.0': 'Bronze',
  'league.1': 'Silver',
  'league.2': 'Gold',
  'league.3': 'Platinum',
  'league.4': 'Diamond',
  'league.label': '{league} League',

  'modes.title': 'Modes',
  'mode.career': 'Career',
  'mode.careerDesc': '5 worlds, 20 routes, 60 stars',
  'mode.daily': 'Daily Route',
  'mode.dailyDesc': 'One route for everyone, new every day',
  'mode.duel': 'Ghost Duel',
  'mode.duelDesc': 'Paste a code, race your friend’s ghost',
  'mode.free': 'Free Flight',
  'mode.freeDesc': 'No score, no gates. Explore and collect postcards',
  'mode.suru': 'SÜRÜ.io',
  'mode.suruDesc': 'Lead thousands of starlings at sunset',
  'mode.suruLeague': 'League Match',
  'mode.suruDay': 'Flock Day',
  'mode.suruPractice': 'Practice',
  'lock.afterRoute': 'Unlocks after route {n}',
  'lock.stars': 'Unlocks at {n} stars',
  'lock.rank': 'Unlocks at rank {n}',

  'intro.daily.title': 'Daily Route unlocked',
  'intro.daily.body': 'Everyone flies the same route; a new one arrives each day and your best time is the one you share.',
  'intro.suru.title': 'SÜRÜ.io unlocked',
  'intro.suru.body': 'Lead thousands of starlings with one finger; nobody is eaten, rivals are won over.',
  'intro.duel.title': 'Ghost Duel unlocked',
  'intro.duel.body': 'Send your flight as a code; it flies as your ghost on your friend’s screen.',
  'intro.free.title': 'Free Flight unlocked',
  'intro.free.body': 'No score and no gates; explore the land and collect all 25 postcards.',
  'intro.weekly.title': 'Route of the Week',
  'intro.weekly.body': 'A familiar route is waiting for you under different skies this week.',
  'intro.action': 'Show me',

  'daily.title': 'Daily Route',
  'daily.number': '#{n}',
  'daily.best': 'Your best today',
  'daily.none': 'Not flown today',
  'daily.attempts': '{n, plural, one {# attempt} other {# attempts}}',
  'daily.botTime': 'Master time',
  'daily.rules': 'Timed from jump to touchdown. Each missed gate adds 2.0\u00A0s.',
  'daily.next': 'New route at midnight (Türkiye time)',
  'daily.gates': '{n} gates',
  'daily.dayOfWeek': 'Difficulty {n}',
  'daily.attemptsLabel': 'Attempts',
  'daily.difficultyLabel': 'Difficulty',

  'duel.title': 'Ghost Duel',
  'duel.hint': 'Your friend’s flight flies with you as a ghost. No collisions, just the race.',
  'duel.codeLabel': 'Duel code',
  'duel.placeholder': 'KNT1-…',
  'duel.load': 'Load ghost',
  'duel.ghostOf': '{name, possessive} ghost',
  'duel.ghostLine': '{ghost} · {route} · {metric}',
  'duel.race': 'Race',
  'duel.verifying': 'Verifying code',
  'duel.err.invalid': 'Invalid code. Make sure you copied all of it.',
  'duel.err.version': 'This code was recorded with a different version of the game.',
  'duel.err.empty': 'Paste a code first.',
  'duel.err.clipboard': 'Couldn’t read the clipboard; paste the code into the box.',
  'duel.routeDaily': 'Daily Route #{n}',
  'duel.oneTime': 'This world isn’t unlocked yet; you can fly it once for the duel.',

  'pause.title': 'Paused',
  'pause.resume': 'Resume',
  'pause.restart': 'Restart',
  'pause.photo': 'Photo Mode',
  'pause.settings': 'Settings',
  'pause.quit': 'Quit',

  'results.complete': 'Route complete',
  'results.half': 'Half Flight',
  'results.halfNote': 'Land by parachute in the landing zone to earn stars and records.',
  'results.newBest': 'New best',
  'results.pbDelta': 'Best {d}',
  'results.ghostDelta': 'Ghost {d} s',
  'results.row.proximity': 'Proximity',
  'results.row.grazes': 'Skims ×{n}',
  'results.row.gates': 'Gates {a}/{b}',
  'results.row.balloon': 'Balloon Thread ×{n}',
  'results.row.thermal': 'Thermals ×{n}',
  'results.row.landing': 'Landing · {m} m',
  'results.row.soft': 'Soft Landing',
  'results.row.bold': 'Bold Opening',
  'results.row.missed': 'Missed gates ×{n}',
  'results.row.flight': 'Flight time',
  'results.total': 'Total',
  'results.retry': 'Retry',
  'results.share': 'Share',
  'results.duelCode': 'Duel Code',
  'results.next': 'Next',
  'results.rematch': 'Rematch Code',
  'results.duelWin': 'You won · {d} s',
  'results.duelLose': 'You lost · {d} s',
  'results.duelTie': 'Dead heat',
  'results.codeCopied': 'Code copied',
  'results.assist': 'Assisted',
  'results.slow': 'Slow Mode',
  'results.taskDone': 'Done',

  'settings.title': 'Settings',
  'settings.sec.general': 'General',
  'settings.sec.sound': 'Sound',
  'settings.sec.access': 'Accessibility',
  'settings.graphics': 'Graphics',
  'settings.q.auto': 'Auto',
  'settings.q.autoNow': 'now: {tier}',
  'settings.q.ultra': 'Ultra',
  'settings.q.high': 'High',
  'settings.q.medium': 'Medium',
  'settings.q.low': 'Low',
  'settings.fps': 'FPS',
  'settings.fps30sub': 'Battery saver',
  'settings.ultra120': 'Ultra 120 Hz',
  'settings.ultra120Sub': 'On high refresh rate displays',
  'settings.master': 'Master volume',
  'settings.music': 'Music',
  'settings.sfx': 'Effects',
  'settings.haptics': 'Vibration',
  'settings.haptics.on': 'On',
  'settings.haptics.low': 'Low',
  'settings.haptics.off': 'Off',
  'settings.lang': 'Language',
  'settings.lang.tr': 'Türkçe',
  'settings.lang.en': 'English',
  'settings.reduceMotion': 'Reduce motion',
  'settings.reduceMotionSub': 'Screen shake and slow motion are toned down',
  'settings.leftHanded': 'Left-handed mode',
  'settings.leftHandedSub': 'Parachute, pause and gauges are mirrored',
  'settings.sec.flight': 'Flight controls',
  'settings.sec.camera': 'Camera and HUD',
  'settings.sec.assist': 'Assistance',
  'settings.controlDir': 'Control direction',
  'settings.controlDir.natural': 'Natural',
  'settings.controlDir.pilot': 'Pilot',
  'settings.controlDir.naturalSub': 'Drag up, nose up',
  'settings.controlDir.pilotSub': 'Drag up, nose down',
  'settings.sensitivity': 'Sensitivity',
  'settings.expo': 'Expo',
  'settings.expoSub': 'Finer control around centre',
  'settings.gyro': 'Gyroscope',
  'settings.gyro.off': 'Off',
  'settings.gyro.roll': 'Roll',
  'settings.gyro.full': 'Full',
  'settings.twoThumbs': 'Two thumbs',
  'settings.twoThumbsSub': 'Landscape: left half rolls, right half pitches',
  'settings.cameraDistance': 'Camera distance',
  'settings.cam.near': 'Near',
  'settings.cam.normal': 'Normal',
  'settings.cam.far': 'Far',
  'settings.helmetCam': 'Helmet camera',
  'settings.helmetCamSub': 'First person, level horizon',
  'settings.comfortCamera': 'Comfort camera',
  'settings.comfortCameraSub': 'Less banking, no shake, soft vignette',
  'settings.bigHud': 'Large HUD',
  'settings.colorBlind': 'Colour-blind mode',
  'settings.colorBlindSub': 'Okabe-Ito colours, slices thicken by tier',
  'settings.flightAssist': 'Flight assist',
  'settings.assist.full': 'Full',
  'settings.assist.low': 'Low',
  'settings.assist.off': 'Off',
  'settings.assistSub': '{a, select, full {Gentle nudges and gate magnet} low {Crash warning only} other {No assistance}}',
  'settings.autoParachute': 'Auto parachute',
  'settings.autoParachuteSub': 'Opens at the ideal height; landing bonus is halved',
  'settings.slowMode': 'Slow mode',
  'settings.slowModeSub': 'Sim speed 0.8× · Career and Free Flight only',
  'settings.sec.about': 'About',
  'about.reality': 'In real life, wingsuit flying takes years of training.',
  'about.credits': 'Credits and data sources',
  'about.version': 'Version {v}',
  'about.respect': 'Made with respect for the landscapes of Anatolia.',

  'collection.title': 'Collection',
  'collection.postcards': 'Postcards',
  'collection.wardrobe': 'Wardrobe',
  'collection.badges': 'Badges',
  'collection.count': '{n}/{total}',
  'collection.missing': 'Not found yet',
  'collection.postcardHint': 'Capture it in Photo Mode during Free Flight.',
  'collection.patterns': 'Pattern',
  'collection.palettes': 'Palette',
  'collection.trails': 'Trail',
  'collection.equipped': 'Equipped',
  'collection.equip': 'Equip',
  'collection.earned': 'Earned',
  'collection.setBonus': 'All five postcards: {pattern} pattern',
  'source.start': 'Starter',
  'source.usta': 'Master Task · {route}',
  'source.rank': 'Rank {n}',
  'source.postcards': '{world} postcard set',
  'source.weekly': 'Route of the Week',
  'source.log': 'Flight Log · 7 stamps',

  'photo.title': 'Photo Mode',
  'photo.fov': 'FOV',
  'photo.roll': 'Roll',
  'photo.exposure': 'Exposure',
  'photo.focus': 'Focus',
  'photo.aperture': 'Aperture',
  'photo.filter': 'Filter',
  'photo.grain': 'Grain',
  'photo.frame': 'Frame',
  'photo.logo': 'Logo',
  'photo.hideUi': 'Hide interface',
  'photo.save': 'Save',
  'photo.saved': 'Saved to gallery',
  'photo.postcardFound': 'Postcard found',
  'photo.tapToShow': 'Tap to show',
  'filter.natural': 'Natural',
  'filter.golden': 'Golden Hour',
  'filter.documentary': 'Documentary',
  'filter.postcard': 'Postcard',
  'filter.coldMorning': 'Cold Morning',
  'filter.bw': 'Black & White',

  'help.title': 'Help with this section?',
  'help.full': 'Full Assist',
  'help.fullSub': 'Gentle nudges away from impacts',
  'help.line': 'Guide Line',
  'help.lineSub': 'The master pilot’s line is shown in light',
  'help.no': 'No thanks',
  'inverted.title': 'Inverted?',
  'inverted.sub': 'Flip the up and down controls?',
  'assistOff.title': 'Turn assistance off?',
  'assistOff.yes': 'Turn off',
  'assistOff.no': 'Keep it on',
  'resume.title': 'Resume',
  'resume.sub': 'Tap to carry on where you left off',
  'toast.mediumSuggested': 'Medium is recommended for smoothness',
  'toast.copied': 'Copied to clipboard',

  'hud.parachute': 'Parachute',
  'hud.speedUnit': 'km/h',
  'hud.altUnit': 'm',
  'hud.graze': 'Skim',
  'hud.balloon': 'Balloon Thread',
  'hud.gate': 'Gate',
  'hud.chain': 'Chain ×{n}',
  'hud.thermal': 'Thermal',
  'hud.gateMissed': 'Gate missed',
  'hud.landed': 'Landing',
  'hud.soft': 'Soft Landing',
  'hud.bold': 'Bold Opening',
  'hud.emergency': 'Emergency Chute',
  'hud.pause': 'Pause',
  'ftue.jump': 'Jump',
  'ftue.pull': 'Pull',

  'suru.title': 'SÜRÜ.io',
  'suru.tagline': 'Lead thousands of starlings with one finger as the sun goes down.',
  'suru.leagueDesc': 'Three minutes against AI flocks',
  'suru.dayDesc': 'Same arena and wind for everyone',
  'suru.practiceDesc': 'Only Shy and Gatherer flocks',
  'suru.aiLabel': 'AI flocks',
  'suru.lp': '{n} LP',
  'suru.nextLeague': '{n} LP to {league}',
  'suru.topLeague': 'Top league',
  'flock.0': 'Lodos Flock',
  'flock.1': 'Moonpath',
  'flock.2': 'Red Wing',
  'flock.3': 'Poyraz',
  'flock.4': 'Karayel',
  'flock.5': 'Sea Sparkle',
  'flock.6': 'Reed Flock',
  'flock.7': 'Breeze',
  'flock.8': 'Imbat',
  'flock.9': 'East Wind',
  'flock.10': 'Daybreak',
  'flock.11': 'Evening Star',
  'flock.12': 'Turtle Dove Flock',
  'flock.13': 'Lighthouse Cape',
  'flock.14': 'Tide',
  'flock.15': 'Northern Light',

  'pc.w1p1': 'Pigeon Valley Dawn',
  'pc.w1p2': 'The Three Beauties',
  'pc.w1p3': 'Red Valley',
  'pc.w1p4': 'Balloon Field',
  'pc.w1p5': 'Uçhisar Silhouette',
  'pc.w2p1': 'Hidden Cove',
  'pc.w2p2': 'Rock Tombs',
  'pc.w2p3': 'Gulet Harbour',
  'pc.w2p4': 'Rock Arch',
  'pc.w2p5': 'Cliffside Lighthouse',
  'pc.w3p1': 'Sea of Clouds',
  'pc.w3p2': 'Waterfall Curtain',
  'pc.w3p3': 'Highland Morning',
  'pc.w3p4': 'Spruce Cathedral',
  'pc.w3p5': 'Lake Mirror',
  'pc.w4p1': 'Summit Ridge',
  'pc.w4p2': 'Ice Cornice',
  'pc.w4p3': 'Snow Wave',
  'pc.w4p4': 'Shadow Valley',
  'pc.w4p5': 'Stardust',
  'pc.w5p1': 'Travertine Terraces',
  'pc.w5p2': 'Mirror Pools',
  'pc.w5p3': 'Ancient Theatre',
  'pc.w5p4': 'Crimson Horizon',
  'pc.w5p5': 'Last Light',

  'badge.firstJump': 'First Jump',
  'badge.firstJump.desc': 'Finish your first route.',
  'badge.threeMetre': '3 Metre Club',
  'badge.threeMetre.desc': '10 s total at ×5 in one flight.',
  'badge.cloudPiercer': 'Cloud Piercer',
  'badge.cloudPiercer.desc': 'Three-star Sea of Clouds.',
  'badge.zeroContact': 'Zero Contact',
  'badge.zeroContact.desc': 'Earn three stars without a touch.',
  'badge.sunsetPilot': 'Sunset Pilot',
  'badge.sunsetPilot.desc': 'Finish all four Pamukkale routes.',
  'badge.postcardHunter': 'Postcard Hunter',
  'badge.postcardHunter.desc': 'Collect all 25 postcards.',
  'badge.flockLeader': 'Flock Leader',
  'badge.flockLeader.desc': 'Finish first in a SÜRÜ.io round.',
  'badge.encircleMaster': 'Encircle Master',
  'badge.encircleMaster.desc': 'Encircle three times in one round.',
  'badge.diamondWing': 'Diamond Wing',
  'badge.diamondWing.desc': 'Reach the Diamond league.',
  'badge.balloonFriend': 'Balloon Friend',
  'badge.balloonFriend.desc': 'Five Balloon Threads in one flight.',
  'badge.gateChain': 'Unbroken Chain',
  'badge.gateChain.desc': 'Clear every gate of a route in one chain.',
  'badge.thermalWolf': 'Thermal Wolf',
  'badge.thermalWolf.desc': 'Ride three thermals in one flight.',
  'badge.dawnRider': 'Dawn Rider',
  'badge.dawnRider.desc': 'Collect all 12 Cappadocia stars.',
  'badge.turquoiseShadow': 'Turquoise Shadow',
  'badge.turquoiseShadow.desc': 'Fly 5 s within 4 m of Lycian water.',
  'badge.highlandWind': 'Highland Wind',
  'badge.highlandWind.desc': 'Collect all 12 Black Sea stars.',
  'badge.snowBird': 'Snow Bird',
  'badge.snowBird.desc': 'Collect all 12 Erciyes stars.',
  'badge.mirrorFlight': 'Mirror Flight',
  'badge.mirrorFlight.desc': 'Hold ×5 for 3 s over the Mirror Pools.',
  'badge.bullseye': 'Bullseye',
  'badge.bullseye.desc': 'Land within 2 m of the target.',
  'badge.featherlight': 'Featherlight',
  'badge.featherlight.desc': 'Make ten soft landings.',
  'badge.boldOpening': 'Bold Canopy',
  'badge.boldOpening.desc': 'Make ten Bold Openings.',
  'badge.flightLog': 'Flight Log',
  'badge.flightLog.desc': 'Collect seven stamps.',
  'badge.pilotOfDay': 'Pilot of the Day',
  'badge.pilotOfDay.desc': 'Three-star a Daily Route.',
  'badge.duelist': 'Duelist',
  'badge.duelist.desc': 'Win a Ghost Duel.',
  'badge.rematch': 'Rematch',
  'badge.rematch.desc': 'Win a duel with a rematch code.',
  'badge.sixtyStars': 'Sixty Stars',
  'badge.sixtyStars.desc': 'Collect all 60 stars.',
  'badge.masterHands': 'Master Hands',
  'badge.masterHands.desc': 'Complete all 60 Master Tasks.',
  'badge.legend': 'Legend',
  'badge.legend.desc': 'Reach Pilot Rank 44.',
  'badge.quietGlide': 'Quiet Glide',
  'badge.quietGlide.desc': 'Spend ten minutes in Free Flight.',
  'badge.shutterbug': 'Shutterbug',
  'badge.shutterbug.desc': 'Save your first Photo Mode shot.',
  'badge.untilSunset': 'Until Sunset',
  'badge.untilSunset.desc': 'Stay in a SÜRÜ.io round until sunset.',

  'pattern.kilim': 'Kilim',
  'pattern.cini': 'Tile',
  'pattern.ebru': 'Marbling',
  'pattern.periBacasi': 'Fairy Chimney',
  'pattern.turkuaz': 'Turquoise',
  'pattern.geceYarisi': 'Midnight',
  'pattern.balonSeridi': 'Balloon Stripe',
  'pattern.karKristali': 'Snow Crystal',
  'pattern.lale': 'Tulip',
  'pattern.traverten': 'Travertine',
  'pattern.ladin': 'Spruce',
  'pattern.dalga': 'Wave',
  'pattern.kontur': 'Contour',
  'pattern.pusula': 'Compass',
  'pattern.guvercin': 'Pigeon',
  'pattern.yakamoz': 'Sea Sparkle',
  'pattern.mehtap': 'Moonpath',
  'pattern.kizilUfuk': 'Crimson Horizon',
  'pattern.sirt': 'Ridgeline',
  'pattern.safak': 'Dawn',
  'palette.safak': 'Dawn',
  'palette.turkuaz': 'Turquoise',
  'palette.yayla': 'Highland',
  'palette.buzul': 'Glacier',
  'palette.gunBatimi': 'Sunset',
  'palette.gece': 'Night',
  'palette.tuf': 'Tuff',
  'palette.bakir': 'Copper',
  'palette.lavanta': 'Lavender',
  'palette.zeytin': 'Olive',
  'palette.kum': 'Sand',
  'palette.komur': 'Charcoal',
  'trail.dumanBeyazi': 'Smoke White',
  'trail.altinToz': 'Gold Dust',
  'trail.ebruAkisi': 'Marbled Flow',
  'trail.buzKristali': 'Ice Crystal',
  'trail.kirlangic': 'Swallow',
  'trail.laleYapragi': 'Tulip Petal',
  'trail.turkuazKopuk': 'Turquoise Foam',
  'trail.sisTulu': 'Mist Veil',
  'trail.brulorIsigi': 'Burner Glow',
  'trail.maviSaat': 'Blue Hour',

  'share.daily': 'Daily Route',
  'share.prox': 'Proximity',
  'share.duel': 'Duel',
  'share.suru.day': 'Flock Day',
  'share.suru.league': 'League Match',
  'share.suru.practice': 'Practice',
  'share.suru.peak': 'Peak {n, number} birds',
  'share.suru.encircle': 'Encircle ×{n}',
  'share.suru.survived': 'Survived to sunset',
  'share.suru.place': '{p, ordinal}/{n}',
  'share.cardTitle': 'KANAT',

  'month.1': 'January',
  'month.2': 'February',
  'month.3': 'March',
  'month.4': 'April',
  'month.5': 'May',
  'month.6': 'June',
  'month.7': 'July',
  'month.8': 'August',
  'month.9': 'September',
  'month.10': 'October',
  'month.11': 'November',
  'month.12': 'December',
  'date.long': '{d} {month} {y}',
};
