// Turkish UI strings (default language). Message syntax (see src/ui/i18n.ts):
//   {name} · {n, number} · {n, decimal} · {t, time} · {d, delta} · {name, possessive} · {n, ordinal}
//   {n, plural, one {…#…} other {…#…}} · {x, select, a {…} other {…}}
// Never build sentences by concatenation; add a key instead. Uppercase via upper() (tr-TR), never CSS.
export const TR = {
  // ---- common ----
  'app.name': 'KANAT',
  'app.tagline': 'Anadolu’nun manzaralarında kanat giysisiyle süzül.',
  'common.ok': 'Tamam',
  'common.cancel': 'Vazgeç',
  'common.back': 'Geri',
  'common.close': 'Kapat',
  'common.continue': 'Devam',
  'common.yes': 'Evet',
  'common.no': 'Hayır',
  'common.play': 'Uç',
  'common.retry': 'Tekrar',
  'common.share': 'Paylaş',
  'common.next': 'Sonraki',
  'common.settings': 'Ayarlar',
  'common.locked': 'Kilitli',
  'common.new': 'Yeni',
  'common.apply': 'Uygula',
  'common.copy': 'Kopyala',
  'common.copied': 'Kopyalandı',
  'common.paste': 'Yapıştır',
  'common.stars': '{n} yıldız',
  'common.starsOf': '{n}/{total}',
  'common.route': 'Rota {n}',
  'common.difficulty': 'Zorluk {n}/9',
  'common.score': 'Puan',
  'common.time': 'Süre',
  'common.best': 'En iyi',
  'common.points': '{n, number} puan',
  'common.seconds': '{n, decimal} sn',
  'common.metres': '{n} m',
  'common.ai': 'YZ',

  // ---- loading ----
  'loading.title': 'Yükleniyor',
  'loading.preparing': 'Arazi hazırlanıyor',
  'loading.tip': 'İpucu',
  'tip.0': 'Yakın geç, puan katlanır: 3 metrenin altı ×5.',
  'tip.1': 'Bırakmak her zaman güvenlidir; kanatlar kendiliğinden düzelir.',
  'tip.2': 'Termaller enerjini yeniler. Havadaki ısı titreşimini ara.',
  'tip.3': 'İki balonun arasından geç: Balon İlmeği +750.',
  'tip.4': 'Paraşütü 60–90 metrede açarsan Cesur Açılış bonusu kazanırsın.',
  'tip.5': 'Yere 3 metre kala aşağı çek: yumuşak iniş.',
  'tip.6': 'Kısa çizgi çoğu zaman yakın çizgidir.',
  'tip.7': 'Günün Rotası herkes için aynı. Kartını paylaş, kıyasla.',
  'tip.8': 'Düello kodunu gönder; uçuşun arkadaşının ekranında hayalet olur.',
  'tip.9': 'SÜRÜ.io’da kimse yenmez: halkayı kapat, sürüyü ikna et.',

  // ---- main menu ----
  'menu.continue': 'Devam',
  'menu.continueSub': '{world}\u00A0· Rota\u00A0{n}',
  'menu.firstFlight': 'İlk uçuş',
  'menu.firstFlightSub': 'Kapadokya şafağında balon sepetinden atla',
  'menu.daily': 'Günün Rotası',
  'menu.dailyBest': 'En iyi {time, time}',
  'menu.dailyNotYet': 'Bugün henüz uçmadın',
  'menu.modes': 'Modlar',
  'menu.modesSub': 'Kariyer\u00A0· Düello\u00A0· Serbest\u00A0Uçuş',
  'menu.suru': 'SÜRÜ.io',
  'menu.suruSub': '{league} · {lp} LP',
  'menu.collection': 'Koleksiyon',
  'menu.collectionSub': '{postcards}/25 kartpostal\u00A0· {badges}/30\u00A0rozet',
  'menu.rank': 'Rütbe {level}',
  'menu.worlds': 'Dünyalar',
  'menu.locked': '{cond}',

  // ---- worlds ----
  'worlds.title': 'Dünyalar',
  'worlds.stars': '{n}/{total}',
  'worlds.unlockAt': '{n} yıldızla açılır',
  'worlds.needMore': '{n} yıldız daha',
  'worlds.open': 'Rotalar',
  'worlds.index': 'Dünya {n}',
  'world.kapadokya': 'Kapadokya Şafağı',
  'world.likya': 'Likya Kıyısı',
  'world.karadeniz': 'Karadeniz Yaylası',
  'world.erciyes': 'Erciyes Karı',
  'world.pamukkale': 'Pamukkale Gün Batımı',
  'worldShort.kapadokya': 'Kapadokya',
  'worldShort.likya': 'Likya',
  'worldShort.karadeniz': 'Karadeniz',
  'worldShort.erciyes': 'Erciyes',
  'worldShort.pamukkale': 'Pamukkale',
  'worldTag.kapadokya': 'Şafak, altın sis ve kırk balon',
  'worldTag.likya': 'İkindi ışığında turkuaz koylar',
  'worldTag.karadeniz': 'Bulut denizinin altında yayla',
  'worldTag.erciyes': 'Kış ikindisinde mavi gölgeler',
  'worldTag.pamukkale': 'Gün batımında ayna havuzlar',
  'worldIntro.likya': 'Yalıyardan dal, berrak suyun dört metre üstünden gölgenle yarış.',
  'worldIntro.karadeniz': 'Bulut denizine gömül, şelalenin önünden yaylaya fırla.',
  'worldIntro.erciyes': 'Kar sırtlarının yanından geç, kornişlerin altından süzül.',
  'worldIntro.pamukkale': 'Gün batımını yansıtan havuzların üstünde kendi yansımanla uç.',
  'worldIntro.title': '{world} açıldı',
  'geo.lat': '{v}° K',
  'geo.lon': '{v}° D',

  // ---- routes ----
  'routes.title': 'Rotalar',
  'routes.tasks': 'Usta Görevleri',
  'routes.bestScore': 'En iyi puan',
  'routes.bestTime': 'En iyi süre',
  'routes.noBest': 'Henüz uçulmadı',
  'routes.fly': 'Uç',
  'routes.locked': 'Önceki rotayı bitir',
  'routes.jumpFrom': '{type, select, balon {Balon sepetinden atlayış} ucurum {Yalıyar tepesinden atlayış} other {Sırt çıkıntısından atlayış}}',
  'route.w1r1': 'İlk Atlayış',
  'route.w1r2': 'Peri Bacaları Slalomu',
  'route.w1r3': 'Balon Yolu',
  'route.w1r4': 'Güvercinlik Kanyonu',
  'route.w2r1': 'Yalıyar Süzülüşü',
  'route.w2r2': 'Gulet Koyu',
  'route.w2r3': 'Kaya Kemeri',
  'route.w2r4': 'Mezar Cepheleri Hattı',
  'route.w3r1': 'Bulut Denizi',
  'route.w3r2': 'Ladin Koridoru',
  'route.w3r3': 'Şelale Perdesi',
  'route.w3r4': 'Yayla Alçak Geçişi',
  'route.w4r1': 'Kar Sırtı',
  'route.w4r2': 'Korniş Kenarı',
  'route.w4r3': 'Buzul Oluğu',
  'route.w4r4': 'Zirve İnişi',
  'route.w5r1': 'Traverten Basamakları',
  'route.w5r2': 'Antik Tiyatro Üstü',
  'route.w5r3': 'Ayna Havuzlar',
  'route.w5r4': 'Gün Batımı Finali',

  // ---- usta task templates (§2.5) ----
  'usta.balloonThread': '{count} Balon İlmeği',
  'usta.mult5Hold': '×5’te kesintisiz {value} sn',
  'usta.grazeCount': 'Tek uçuşta {count} Sıyırma',
  'usta.noContact3Stars': 'Hiç temas etmeden 3 yıldız',
  'usta.landWithin': 'Hedefin {value} m içine in',
  'usta.noThermal': 'Termal kullanmadan bitir',
  'usta.gateChain': '{count} kapılık zincir kur',
  'usta.allGates': 'Tüm kapılardan geç',
  'usta.softLanding': 'Yumuşak iniş yap',
  'usta.boldOpen': 'Cesur Açılış (60–90 m)',
  'usta.scoreOver': '{value, number} puanı geç',
  'usta.prox3Time': '×3 ve üstünde toplam {value} sn',
  'usta.speedOver': '{value} km/s’yi geç',
  'usta.thermalCount': '{count} termal kullan',
  'usta.timeUnder': '{value} saniyenin altında bitir',
  'usta.waterSkim': 'Suyun 4 m üstünde {value} sn uç',
  'usta.cloudDive': 'Bulut denizine dal ve çık',
  'usta.noBounce': 'Hiç sekmeden bitir',
  'usta.generic': 'Usta Görevi',

  // ---- rank / league ----
  'rank.0': 'Çaylak',
  'rank.1': 'Süzülen',
  'rank.2': 'Sıyırıcı',
  'rank.3': 'Kartal',
  'rank.4': 'Usta',
  'rank.5': 'Efsane',
  'rank.level': 'Seviye {n}',
  'rank.label': 'Pilot Rütbesi',
  'rank.xp': '{xp, number}/{next, number} XP',
  'league.0': 'Bronz',
  'league.1': 'Gümüş',
  'league.2': 'Altın',
  'league.3': 'Platin',
  'league.4': 'Elmas',
  'league.label': '{league} Lig',

  // ---- modes ----
  'modes.title': 'Modlar',
  'mode.career': 'Kariyer',
  'mode.careerDesc': '5 dünya, 20 rota, 60 yıldız',
  'mode.daily': 'Günün Rotası',
  'mode.dailyDesc': 'Herkese aynı rota, her gün yeni',
  'mode.duel': 'Hayalet Düello',
  'mode.duelDesc': 'Kodu yapıştır, arkadaşının hayaletiyle yarış',
  'mode.free': 'Serbest Uçuş',
  'mode.freeDesc': 'Puan yok, kapı yok. Keşfet, kartpostal topla',
  'mode.suru': 'SÜRÜ.io',
  'mode.suruDesc': 'Gün batarken binlerce sığırcığı yönet',
  'mode.suruLeague': 'Lig Maçı',
  'mode.suruDay': 'Sürü Günü',
  'mode.suruPractice': 'Antrenman',
  'lock.afterRoute': '{n}. rotayı bitirince açılır',
  'lock.stars': '{n} yıldızla açılır',
  'lock.rank': 'Rütbe {n}’de açılır',

  // ---- unlock intro cards (one sentence each) ----
  'intro.daily.title': 'Günün Rotası açıldı',
  'intro.daily.body': 'Herkes aynı rotayı uçar; her gün yenisi gelir, en iyi süren paylaşılır.',
  'intro.suru.title': 'SÜRÜ.io açıldı',
  'intro.suru.body': 'Binlerce sığırcığı tek parmakla yönet; kimse yenmez, rakipler ikna edilir.',
  'intro.duel.title': 'Hayalet Düello açıldı',
  'intro.duel.body': 'Uçuşunu kod olarak gönder; arkadaşının ekranında hayaletin olarak uçar.',
  'intro.free.title': 'Serbest Uçuş açıldı',
  'intro.free.body': 'Puan da kapı da yok; manzarayı keşfet ve 25 kartpostalı topla.',
  'intro.weekly.title': 'Haftanın Rotası',
  'intro.weekly.body': 'Bilindik bir rota, bu hafta değişik bir havayla seni bekliyor.',
  'intro.action': 'Göster',

  // ---- daily ----
  'daily.title': 'Günün Rotası',
  'daily.number': '#{n}',
  'daily.best': 'Bugünkü en iyin',
  'daily.none': 'Bugün henüz uçmadın',
  'daily.attempts': '{n} deneme',
  'daily.botTime': 'Usta süresi',
  'daily.rules': 'Süre atlayıştan ayak temasına kadar. Kaçırılan her kapı +2,0\u00A0sn.',
  'daily.next': 'Yeni rota gece yarısı (TSİ)',
  'daily.gates': '{n} kapı',
  'daily.dayOfWeek': 'Zorluk {n}',
  'daily.attemptsLabel': 'Deneme',
  'daily.difficultyLabel': 'Zorluk',

  // ---- duel ----
  'duel.title': 'Hayalet Düello',
  'duel.hint': 'Arkadaşının uçuşu hayalet olarak seninle uçar. Çarpışma yok, yalnız yarış.',
  'duel.codeLabel': 'Düello kodu',
  'duel.placeholder': 'KNT1-…',
  'duel.load': 'Hayaleti yükle',
  'duel.ghostOf': '{name, possessive} hayaleti',
  'duel.ghostLine': '{ghost} · {route} · {metric}',
  'duel.race': 'Yarış',
  'duel.verifying': 'Kod doğrulanıyor',
  'duel.err.invalid': 'Kod geçersiz. Kodu eksiksiz kopyaladığından emin ol.',
  'duel.err.version': 'Bu kod oyunun farklı bir sürümüyle kaydedilmiş.',
  'duel.err.empty': 'Önce bir kod yapıştır.',
  'duel.err.clipboard': 'Pano okunamadı; kodu kutuya yapıştır.',
  'duel.routeDaily': 'Günün Rotası #{n}',
  'duel.oneTime': 'Bu dünya henüz açık değil; düello için bir kez uçabilirsin.',

  // ---- pause ----
  'pause.title': 'Duraklatıldı',
  'pause.resume': 'Devam',
  'pause.restart': 'Yeniden',
  'pause.photo': 'Foto Modu',
  'pause.settings': 'Ayarlar',
  'pause.quit': 'Çık',

  // ---- results ----
  'results.complete': 'Rota tamamlandı',
  'results.half': 'Yarım Uçuş',
  'results.halfNote': 'Yıldız ve rekor için iniş bölgesine paraşütle in.',
  'results.newBest': 'Yeni rekor',
  'results.pbDelta': 'Rekor {d}',
  'results.ghostDelta': 'Hayalet {d} sn',
  'results.row.proximity': 'Yakınlık',
  'results.row.grazes': 'Sıyırma ×{n}',
  'results.row.gates': 'Kapılar {a}/{b}',
  'results.row.balloon': 'Balon İlmeği ×{n}',
  'results.row.thermal': 'Termal ×{n}',
  'results.row.landing': 'İniş · {m} m',
  'results.row.soft': 'Yumuşak İniş',
  'results.row.bold': 'Cesur Açılış',
  'results.row.missed': 'Kaçırılan kapı ×{n}',
  'results.row.flight': 'Uçuş süresi',
  'results.total': 'Toplam',
  'results.retry': 'Tekrar',
  'results.share': 'Paylaş',
  'results.duelCode': 'Düello Kodu',
  'results.next': 'Sonraki',
  'results.rematch': 'Rövanş Kodu',
  'results.duelWin': 'Kazandın · {d} sn',
  'results.duelLose': 'Kaybettin · {d} sn',
  'results.duelTie': 'Berabere',
  'results.codeCopied': 'Kod kopyalandı',
  'results.assist': 'Yardımla',
  'results.slow': 'Yavaş Mod',
  'results.taskDone': 'Tamam',

  // ---- settings: common core ----
  'settings.title': 'Ayarlar',
  'settings.sec.general': 'Genel',
  'settings.sec.sound': 'Ses',
  'settings.sec.access': 'Erişilebilirlik',
  'settings.graphics': 'Grafik',
  'settings.q.auto': 'Otomatik',
  'settings.q.autoNow': 'şu an: {tier}',
  'settings.q.ultra': 'Ultra',
  'settings.q.high': 'Yüksek',
  'settings.q.medium': 'Orta',
  'settings.q.low': 'Düşük',
  'settings.fps': 'FPS',
  'settings.fps30sub': 'Pil tasarrufu',
  'settings.ultra120': 'Ultra 120 Hz',
  'settings.ultra120Sub': 'Yüksek yenileme hızlı ekranlarda',
  'settings.master': 'Ana ses',
  'settings.music': 'Müzik',
  'settings.sfx': 'Efektler',
  'settings.haptics': 'Titreşim',
  'settings.haptics.on': 'Açık',
  'settings.haptics.low': 'Az',
  'settings.haptics.off': 'Kapalı',
  'settings.lang': 'Dil',
  'settings.lang.tr': 'Türkçe',
  'settings.lang.en': 'English',
  'settings.reduceMotion': 'Hareketi azalt',
  'settings.reduceMotionSub': 'Ekran sarsıntısı ve ağır çekim kısılır',
  'settings.leftHanded': 'Sol el modu',
  'settings.leftHandedSub': 'Paraşüt, duraklat ve göstergeler aynalanır',
  // ---- settings: KANAT block ----
  'settings.sec.flight': 'Uçuş kontrolü',
  'settings.sec.camera': 'Kamera ve gösterge',
  'settings.sec.assist': 'Yardım',
  'settings.controlDir': 'Kontrol yönü',
  'settings.controlDir.natural': 'Doğal',
  'settings.controlDir.pilot': 'Pilot',
  'settings.controlDir.naturalSub': 'Yukarı sürükle, burun yukarı',
  'settings.controlDir.pilotSub': 'Yukarı sürükle, burun aşağı',
  'settings.sensitivity': 'Hassasiyet',
  'settings.expo': 'Expo',
  'settings.expoSub': 'Merkez çevresinde ince ayar',
  'settings.gyro': 'Jiroskop',
  'settings.gyro.off': 'Kapalı',
  'settings.gyro.roll': 'Yalpa',
  'settings.gyro.full': 'Tam',
  'settings.twoThumbs': 'İki başparmak',
  'settings.twoThumbsSub': 'Yatay ekranda sol yarı yalpa, sağ yarı yunuslama',
  'settings.cameraDistance': 'Kamera mesafesi',
  'settings.cam.near': 'Yakın',
  'settings.cam.normal': 'Normal',
  'settings.cam.far': 'Uzak',
  'settings.helmetCam': 'Kask kamerası',
  'settings.helmetCamSub': 'Birinci şahıs, ufuk sabit',
  'settings.comfortCamera': 'Konfor kamerası',
  'settings.comfortCameraSub': 'Az yatış, sarsıntı yok, yumuşak vinyet',
  'settings.bigHud': 'Büyük HUD',
  'settings.colorBlind': 'Renk körü modu',
  'settings.colorBlindSub': 'Okabe-Ito renkleri, kademeyle kalınlaşan dilimler',
  'settings.flightAssist': 'Uçuş yardımı',
  'settings.assist.full': 'Tam',
  'settings.assist.low': 'Az',
  'settings.assist.off': 'Kapalı',
  'settings.assistSub': '{a, select, full {Yumuşak itme ve kapı mıknatısı} low {Yalnız çarpma uyarısı} other {Yardım yok}}',
  'settings.autoParachute': 'Otomatik paraşüt',
  'settings.autoParachuteSub': 'İdeal yükseklikte açar; iniş bonusu yarıya iner',
  'settings.slowMode': 'Yavaş mod',
  'settings.slowModeSub': 'Sim hızı 0,8× · yalnız Kariyer ve Serbest Uçuş',
  // ---- about ----
  'settings.sec.about': 'Hakkında',
  'about.reality': 'Wingsuit gerçek hayatta yıllar süren eğitim ister.',
  'about.credits': 'Emeği geçenler ve veri kaynakları',
  'about.version': 'Sürüm {v}',
  'about.respect': 'Anadolu’nun manzaralarına saygıyla yapıldı.',

  // ---- collection ----
  'collection.title': 'Koleksiyon',
  'collection.postcards': 'Kartpostallar',
  'collection.wardrobe': 'Giysi Dolabı',
  'collection.badges': 'Rozetler',
  'collection.count': '{n}/{total}',
  'collection.missing': 'Henüz bulunmadı',
  'collection.postcardHint': 'Serbest Uçuş’ta Foto Modu ile çek.',
  'collection.patterns': 'Desen',
  'collection.palettes': 'Palet',
  'collection.trails': 'İz',
  'collection.equipped': 'Giyildi',
  'collection.equip': 'Giy',
  'collection.earned': 'Kazanıldı',
  'collection.setBonus': 'Beş kartpostal: {pattern} deseni',
  'source.start': 'Başlangıç',
  'source.usta': 'Usta Görevi · {route}',
  'source.rank': 'Rütbe {n}',
  'source.postcards': '{world} kartpostal seti',
  'source.weekly': 'Haftanın Rotası',
  'source.log': 'Uçuş Günlüğü · 7 damga',

  // ---- photo mode ----
  'photo.title': 'Foto Modu',
  'photo.fov': 'Görüş',
  'photo.roll': 'Yatış',
  'photo.exposure': 'Pozlama',
  'photo.focus': 'Odak',
  'photo.aperture': 'Diyafram',
  'photo.filter': 'Filtre',
  'photo.grain': 'Gren',
  'photo.frame': 'Çerçeve',
  'photo.logo': 'Logo',
  'photo.hideUi': 'Arayüzü gizle',
  'photo.save': 'Kaydet',
  'photo.saved': 'Galeriye kaydedildi',
  'photo.postcardFound': 'Kartpostal bulundu',
  'photo.tapToShow': 'Göstermek için dokun',
  'filter.natural': 'Doğal',
  'filter.golden': 'Altın Saat',
  'filter.documentary': 'Belgesel',
  'filter.postcard': 'Kartpostal',
  'filter.coldMorning': 'Soğuk Sabah',
  'filter.bw': 'Siyah-Beyaz',

  // ---- in-flight cards ----
  'help.title': 'Bu bölümde yardım?',
  'help.full': 'Tam Yardım',
  'help.fullSub': 'Çarpmaya karşı yumuşak itme',
  'help.line': 'Rehber Hat',
  'help.lineSub': 'Usta pilotun çizgisi ışıkla görünür',
  'help.no': 'Gerek yok',
  'inverted.title': 'Ters mi?',
  'inverted.sub': 'Yukarı-aşağı kontrolünü çevirelim mi?',
  'assistOff.title': 'Yardımı kapatmak ister misin?',
  'assistOff.yes': 'Kapat',
  'assistOff.no': 'Açık kalsın',
  'resume.title': 'Devam',
  'resume.sub': 'Kaldığın yerden sürdürmek için dokun',
  'toast.mediumSuggested': 'Akıcılık için Orta önerilir',
  'toast.copied': 'Panoya kopyalandı',

  // ---- HUD + FTUE ----
  'hud.parachute': 'Paraşüt',
  'hud.speedUnit': 'km/s',
  'hud.altUnit': 'm',
  'hud.graze': 'Sıyırma',
  'hud.balloon': 'Balon İlmeği',
  'hud.gate': 'Kapı',
  'hud.chain': 'Zincir ×{n}',
  'hud.thermal': 'Termal',
  'hud.gateMissed': 'Kapı kaçtı',
  'hud.landed': 'İniş',
  'hud.soft': 'Yumuşak İniş',
  'hud.bold': 'Cesur Açılış',
  'hud.emergency': 'Acil Paraşüt',
  'hud.pause': 'Duraklat',
  'ftue.jump': 'Atla',
  'ftue.pull': 'Çek',

  // ---- SÜRÜ.io menu ----
  'suru.title': 'SÜRÜ.io',
  'suru.tagline': 'Gün batarken binlerce sığırcığı tek parmakla yönet.',
  'suru.leagueDesc': 'Yapay zekâ sürülerine karşı üç dakika',
  'suru.dayDesc': 'Herkese aynı arena, aynı rüzgâr',
  'suru.practiceDesc': 'Yalnız Ürkek ve Toplayıcı sürüler',
  'suru.aiLabel': 'Yapay zekâ sürüleri',
  'suru.lp': '{n} LP',
  'suru.nextLeague': '{league} için {n} LP',
  'suru.topLeague': 'En üst lig',
  'flock.0': 'Lodos Sürüsü',
  'flock.1': 'Mehtap',
  'flock.2': 'Kızıl Kanat',
  'flock.3': 'Poyraz',
  'flock.4': 'Karayel',
  'flock.5': 'Yakamoz',
  'flock.6': 'Sazlık Sürüsü',
  'flock.7': 'Meltem',
  'flock.8': 'İmbat',
  'flock.9': 'Gündoğusu',
  'flock.10': 'Tan Yeri',
  'flock.11': 'Akşam Yıldızı',
  'flock.12': 'Kumru Sürüsü',
  'flock.13': 'Fener Burnu',
  'flock.14': 'Gelgit',
  'flock.15': 'Kuzey Işığı',

  // ---- postcards (§2.5) ----
  'pc.w1p1': 'Güvercinlik Şafağı',
  'pc.w1p2': 'Üçgüzeller',
  'pc.w1p3': 'Kızılçukur',
  'pc.w1p4': 'Balon Tarlası',
  'pc.w1p5': 'Uçhisar Silueti',
  'pc.w2p1': 'Gizli Koy',
  'pc.w2p2': 'Kaya Mezarları',
  'pc.w2p3': 'Gulet Limanı',
  'pc.w2p4': 'Kaya Kemeri',
  'pc.w2p5': 'Yalıyar Feneri',
  'pc.w3p1': 'Bulut Denizi',
  'pc.w3p2': 'Şelale Perdesi',
  'pc.w3p3': 'Yayla Sabahı',
  'pc.w3p4': 'Ladin Katedrali',
  'pc.w3p5': 'Göl Aynası',
  'pc.w4p1': 'Zirve Sırtı',
  'pc.w4p2': 'Buz Kornişi',
  'pc.w4p3': 'Kar Dalgası',
  'pc.w4p4': 'Gölge Vadisi',
  'pc.w4p5': 'Yıldız Tozu',
  'pc.w5p1': 'Traverten Basamakları',
  'pc.w5p2': 'Ayna Havuzlar',
  'pc.w5p3': 'Antik Tiyatro',
  'pc.w5p4': 'Kızıl Ufuk',
  'pc.w5p5': 'Son Işık',

  // ---- badges (30) ----
  'badge.firstJump': 'İlk Atlayış',
  'badge.firstJump.desc': 'İlk rotanı bitir.',
  'badge.threeMetre': '3 Metre Kulübü',
  'badge.threeMetre.desc': 'Tek uçuşta toplam 10 sn ×5.',
  'badge.cloudPiercer': 'Bulut Delen',
  'badge.cloudPiercer.desc': 'Bulut Denizi’ni üç yıldızla bitir.',
  'badge.zeroContact': 'Sıfır Temas',
  'badge.zeroContact.desc': 'Hiç temas etmeden üç yıldız al.',
  'badge.sunsetPilot': 'Gün Batımı Pilotu',
  'badge.sunsetPilot.desc': 'Pamukkale’nin dört rotasını bitir.',
  'badge.postcardHunter': 'Kartpostal Avcısı',
  'badge.postcardHunter.desc': '25 kartpostalın hepsini topla.',
  'badge.flockLeader': 'Sürü Lideri',
  'badge.flockLeader.desc': 'SÜRÜ.io’da bir turu birinci bitir.',
  'badge.encircleMaster': 'Kuşatma Ustası',
  'badge.encircleMaster.desc': 'Tek turda üç Kuşatma yap.',
  'badge.diamondWing': 'Elmas Kanat',
  'badge.diamondWing.desc': 'Elmas lige yüksel.',
  'badge.balloonFriend': 'Balon Dostu',
  'badge.balloonFriend.desc': 'Tek uçuşta beş Balon İlmeği.',
  'badge.gateChain': 'Kesintisiz Zincir',
  'badge.gateChain.desc': 'Bir rotanın tüm kapılarını tek zincirde geç.',
  'badge.thermalWolf': 'Termal Kurdu',
  'badge.thermalWolf.desc': 'Tek uçuşta üç termale gir.',
  'badge.dawnRider': 'Şafak Yolcusu',
  'badge.dawnRider.desc': 'Kapadokya’nın 12 yıldızını topla.',
  'badge.turquoiseShadow': 'Turkuaz Gölge',
  'badge.turquoiseShadow.desc': 'Likya’da suyun 4 m üstünde 5 sn uç.',
  'badge.highlandWind': 'Yayla Rüzgârı',
  'badge.highlandWind.desc': 'Karadeniz’in 12 yıldızını topla.',
  'badge.snowBird': 'Kar Kuşu',
  'badge.snowBird.desc': 'Erciyes’in 12 yıldızını topla.',
  'badge.mirrorFlight': 'Ayna Uçuşu',
  'badge.mirrorFlight.desc': 'Ayna Havuzlar’da ×5 ile 3 sn uç.',
  'badge.bullseye': 'Tam Ortası',
  'badge.bullseye.desc': 'Hedefin 2 m içine in.',
  'badge.featherlight': 'Kuş Tüyü',
  'badge.featherlight.desc': 'On yumuşak iniş yap.',
  'badge.boldOpening': 'Cesur Kanopi',
  'badge.boldOpening.desc': 'On kez Cesur Açılış yap.',
  'badge.flightLog': 'Uçuş Günlüğü',
  'badge.flightLog.desc': 'Yedi damga topla.',
  'badge.pilotOfDay': 'Günün Pilotu',
  'badge.pilotOfDay.desc': 'Günün Rotası’nda üç yıldız al.',
  'badge.duelist': 'Düellocu',
  'badge.duelist.desc': 'Bir Hayalet Düello kazan.',
  'badge.rematch': 'Rövanş',
  'badge.rematch.desc': 'Rövanş koduyla bir düello kazan.',
  'badge.sixtyStars': 'Altmış Yıldız',
  'badge.sixtyStars.desc': '60 yıldızın hepsini topla.',
  'badge.masterHands': 'Usta Eller',
  'badge.masterHands.desc': '60 Usta Görevi’nin hepsini bitir.',
  'badge.legend': 'Efsane',
  'badge.legend.desc': 'Pilot Rütbesi 44’e ulaş.',
  'badge.quietGlide': 'Sakin Süzülüş',
  'badge.quietGlide.desc': 'Serbest Uçuş’ta on dakika geçir.',
  'badge.shutterbug': 'Objektif',
  'badge.shutterbug.desc': 'Foto Modu’nda ilk kareni kaydet.',
  'badge.untilSunset': 'Gün Batımına Kadar',
  'badge.untilSunset.desc': 'SÜRÜ.io’da gün batımına kadar ayakta kal.',

  // ---- cosmetics ----
  'pattern.kilim': 'Kilim',
  'pattern.cini': 'Çini',
  'pattern.ebru': 'Ebru',
  'pattern.periBacasi': 'Peri Bacası',
  'pattern.turkuaz': 'Turkuaz',
  'pattern.geceYarisi': 'Gece Yarısı',
  'pattern.balonSeridi': 'Balon Şeridi',
  'pattern.karKristali': 'Kar Kristali',
  'pattern.lale': 'Lale',
  'pattern.traverten': 'Traverten',
  'pattern.ladin': 'Ladin',
  'pattern.dalga': 'Dalga',
  'pattern.kontur': 'Eşyükselti',
  'pattern.pusula': 'Pusula',
  'pattern.guvercin': 'Güvercin',
  'pattern.yakamoz': 'Yakamoz',
  'pattern.mehtap': 'Mehtap',
  'pattern.kizilUfuk': 'Kızıl Ufuk',
  'pattern.sirt': 'Sırt Çizgisi',
  'pattern.safak': 'Şafak',
  'palette.safak': 'Şafak',
  'palette.turkuaz': 'Turkuaz',
  'palette.yayla': 'Yayla',
  'palette.buzul': 'Buzul',
  'palette.gunBatimi': 'Gün Batımı',
  'palette.gece': 'Gece',
  'palette.tuf': 'Tüf',
  'palette.bakir': 'Bakır',
  'palette.lavanta': 'Lavanta',
  'palette.zeytin': 'Zeytin',
  'palette.kum': 'Kum',
  'palette.komur': 'Kömür',
  'trail.dumanBeyazi': 'Duman Beyazı',
  'trail.altinToz': 'Altın Toz',
  'trail.ebruAkisi': 'Ebru Akışı',
  'trail.buzKristali': 'Buz Kristali',
  'trail.kirlangic': 'Kırlangıç',
  'trail.laleYapragi': 'Lale Yaprağı',
  'trail.turkuazKopuk': 'Turkuaz Köpük',
  'trail.sisTulu': 'Sis Tülü',
  'trail.brulorIsigi': 'Brülör Işığı',
  'trail.maviSaat': 'Mavi Saat',

  // ---- share (text cards; emoji allowed only here) ----
  'share.daily': 'Günün Rotası',
  'share.prox': 'Yakınlık',
  'share.duel': 'Düello',
  'share.suru.day': 'Sürü Günü',
  'share.suru.league': 'Lig Maçı',
  'share.suru.practice': 'Antrenman',
  'share.suru.peak': 'Zirve {n, number} kuş',
  'share.suru.encircle': 'Kuşatma ×{n}',
  'share.suru.survived': 'Gün batımına kadar ayakta',
  'share.suru.place': '{p}./{n}',
  'share.cardTitle': 'KANAT',

  // ---- dates ----
  'month.1': 'Ocak',
  'month.2': 'Şubat',
  'month.3': 'Mart',
  'month.4': 'Nisan',
  'month.5': 'Mayıs',
  'month.6': 'Haziran',
  'month.7': 'Temmuz',
  'month.8': 'Ağustos',
  'month.9': 'Eylül',
  'month.10': 'Ekim',
  'month.11': 'Kasım',
  'month.12': 'Aralık',
  'date.long': '{d} {month} {y}',
} as const;

export type StringKey = keyof typeof TR;
