// world.json schema (public/worlds/<id>/world.json). Owner: terrain agent. Generated by tools/bake-terrain.ts.
// Brief §4.G.7 schema extended with terrain files/extents, light, sky, fog, palette, grading, water and masks.
// Conventions: 1u = 1 m, +y up, +x east, -z north; azimuth 0 = north (-z), clockwise toward east (+x).
// Colors are sRGB hex strings '#rrggbb'; `*Linear` fields are linear-light RGB triplets.

import type { WorldId } from '../sim/types.ts';
import type { GridFileMeta, MaskFileMeta } from '../sim/terrain/decode.ts';

export type { GridFileMeta, MaskFileMeta };
export type Vec3 = [number, number, number];
export type Hex = string;

/** Texture coverage on the XZ plane: uv = ((x - minX) / size, (z - minZ) / size). Image row 0 = north (minZ). */
export interface TexCoverage {
  minX: number;
  minZ: number;
  size: number;
}

export interface WorldConfig {
  id: WorldId;
  /** Schema version of world.json. */
  version: number;
  name: { tr: string; en: string };
  /** UI accent color of the world (§3.5). */
  accent: Hex;
  geo: {
    lat: number;
    lon: number;
    zoomCore: number;
    zoomFar: number;
    coreSizeM: number;
    coreRes: number;
    farSizeM: number;
    farRes: number;
    /** Artistic vertical exaggeration already applied to all stored heights. */
    verticalScale: number;
    /** 'terrarium' = real AWS Terrain Tiles data; 'synthetic' = fBm fallback (dev only). */
    source: 'terrarium' | 'synthetic';
    /** Why this center was chosen (Turkish). */
    note: string;
  };
  hasSea: boolean;
  seaLevel: number;
  terrain: {
    core: GridFileMeta;
    far: GridFileMeta;
    patch: GridFileMeta | null;
    /** Rock mask (u8, same grid as core). Scales the procedural detail D. */
    rock: { file: string; res: number };
    /** Placement masks (u8 interleaved). */
    masks: MaskFileMeta | null;
    /** Collision detail D parameters (mirrors src/sim/terrain/detailNoise.ts — informational). */
    detail: { amp: [number, number]; wavelength: [number, number]; normalOnly: { amp: number; wavelength: number } };
    /** Width (m) of the soft core→far blend band at the core edge (core edge equals far there). */
    coreBlendM: number;
    playBounds: { minX: number; maxX: number; minZ: number; maxZ: number };
    /** Global min/max of the core heights (m, scaled). */
    heightRange: { min: number; max: number };
    /** Pamukkale only: travertine terrace area inside the patch + base lowering rule (§4.G.1). */
    patchInfo: {
      terraceRect: { minX: number; maxX: number; minZ: number; maxZ: number };
      /** Render: lower the core terrain by this much inside the patch rect so the patch sits on top. */
      baseLowerM: number;
      /** Water level offset above the terrace floor (pools are flat meshes). */
      poolDepthM: number;
      /** Pool water surfaces (flat), from the terrace bake. */
      pools: { x: number; z: number; y: number; r: number }[];
    } | null;
  };
  textures: {
    /** RGB8 PNG, octahedral y-up normal of the base core surface: R = px, G = pz (B unused). 1024², core coverage. */
    normal: string;
    /** RGBA8 PNG, 4 layer weights (sum 255), channel i = layers[i]. 1024², core coverage. */
    splat: string;
    /** RGBA8 PNG: R = baked sun shadow (255 lit), G = AO, B = cavity (128 flat, >128 convex), A = rock mask. 1024². */
    shadowAo: string;
    /** Pre-lit macro color (sRGB) 2048² over the core: WebP (single-file build). */
    colorMacro: string;
    /** Same image as KTX2 (ETC1S + mips) for the web build, or null if encoding failed. */
    colorMacroKtx2: string | null;
    /** Pre-lit color 1024² over the far ring (WebP). */
    colorFar: string;
    coverage: { core: TexCoverage; far: TexCoverage; patch: TexCoverage | null };
  };
  /** Splat channel → material layer id. */
  layers: [string, string, string, string];
  /** Base albedo (sRGB) per layer, same order as `layers`. */
  layerColors: [Hex, Hex, Hex, Hex];
  /** PBR roughness per layer (§3.3). */
  layerRoughness: [number, number, number, number];
  sun: {
    azimuthDeg: number;
    elevationDeg: number;
    /** Unit vector pointing TOWARD the sun (world space). */
    dir: Vec3;
    kelvin: number;
    color: Hex;
    colorLinear: Vec3;
    /** Suggested directional light intensity (three.js physically-unscaled units). */
    intensity: number;
  };
  sky: {
    kelvin: number;
    zenith: Hex;
    horizon: Hex;
    /** Color right around the sun (scattering halo). */
    sunGlow: Hex;
    /** Ground bounce / lower hemisphere. */
    ground: Hex;
    /** Ambient (hemisphere) intensity suggestion. */
    ambientIntensity: number;
  };
  fog: {
    /** Height fog: density(y) = a * exp(-b * (y - baseY)) (1/m). F integral per brief §4.G.3 with y_cam - baseY. */
    a: number;
    b: number;
    baseY: number;
    color: Hex;
    /** In-scatter color toward the sun (Henyey-Greenstein, g = hgG). */
    sunColor: Hex;
    hgG: number;
    /** Distance (m) at which terrain should be fully fogged on Ultra; other tiers use §5.G view distances. */
    maxViewM: number;
    /** Kapadokya golden valley fog etc. top = absolute y. */
    groundFog: { top: number; density: number; color: Hex } | null;
    /** Karadeniz flyable cloud sea band (absolute y). */
    cloudSea: { bottom: number; top: number; density: number; color: Hex } | null;
  };
  palette: Record<string, Hex>;
  /** Color grading (§3.4), applied after AgX in the uber pass (or in-material on Low). */
  grading: {
    exposure: number;
    lift: Vec3;
    gamma: Vec3;
    gain: Vec3;
    saturation: number;
    contrast: number;
    splitShadow: Hex;
    splitHighlight: Hex;
    /** -1 = all shadows tint, +1 = all highlight tint. */
    splitBalance: number;
    vignette: number;
  };
  water: {
    enabled: boolean;
    level: number;
    shallow: Hex;
    deep: Hex;
    /** Depth (m) at which water reaches the deep color. */
    depthFalloffM: number;
    foam: Hex;
    roughness: number;
    /** Pamukkale pools / lakes use a separate calm-mirror look. */
    kind: 'sea' | 'pools' | 'none';
  };
  wind: { dirDeg: number; speed: number };
  /** Exact lighting model used to pre-light color_macro/color_far (so near-terrain shading can match). */
  bakeLighting: {
    sunColorLinear: Vec3;
    skyColorLinear: Vec3;
    sunStrength: number;
    ambientStrength: number;
    /** litRGB = albedo * (ambientStrength*skyColor*ao + sunStrength*sunColor*shadow*ndlRel) where ndlRel = wrap(N·L)/sin(elev). */
    formula: string;
  };
  /** Prop/vegetation hints consumed by src/sim/world/props.ts (flight agent) — counts and mask channel names. */
  props: Record<string, { count?: number; mask?: string; seed?: number }>;
}

export const WORLD_JSON_VERSION = 1;
